### ISSUE TITLE
mongoDB / autorisation IP / droit d'accès (read only ou read-write dans certain cas)

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#10]
Commentaire de Jérôme Servonnat:
 - @Seb: pour exploiter la base depuis python, et notamment avec les Notebooks, nous sommes pour l'instant obligés de se connecter à ciclad puis de lancer le Notebook (via un browser). En termes de performance d'affichage et de manipulation des Notebooks, ce n'est pas vraiment optimal parce qu'un peu lent... Pourrait-on trouver un moyen pour accéder directement à la base depuis un poste fixe, quitte à ce qu'une liste restreinte d'IP soient autorisées?

**Comment by ncaripsl** [comment]
Authentication has been activated on the mongoDB metrics database and 3 users have been created. prodiguer-db-mongo-admin, prodiguer-db-mongo-user and external-db-mongo-exploitation. Passwords have been updated in the json configuration file on each test VM. 

A request has been made to the ISIS team to open the firewall so that the db will be reachable from IPSL labs IP addresses.

One question remain, do the ipython user external-db-mongo-exploitation will neen write access to the metrics db?

**Comment by momipsl** [comment]
AFAIK the external-db-mongo-exploitation will not need write access.

**Comment by ncaripsl** [comment]
ISIS team has just opened the fw

**Comment by ncaripsl** [comment]
VM has been moved to another VLAN and fw has been opened. LSCE helpdesk has to check fw rules.
