### ISSUE TITLE
metrics-formatter and swapping

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#14]
When running the formatter over a large collection of files then the memory usage will increase.

We are experiencing swapping when formatting large collections.

We want to have ease of use when ingesting large collections. I think we can achieve this using 2 Go of RAM and some memory deallocation place at some critical point. I doubt we need 3.2 Go of memory to reformat files.

  PID     USER      PR  NI  VIRT    RES  SHR S %CPU %MEM    TIME+ COMMAND
31786  esg-user 20   0   5395m 3.2g  576 D  4.2    86.3 3:30.62  python

http://stackoverflow.com/questions/15455048/releasing-memory-in-python

[root@prodiguer-test-web ~]# free -m
                     total       used       free     shared    buffers cached
Mem:          3832       3724        107          0 2         10
-/+ buffers/cache:       3712        120
Swap:         4095       2047       2048

**Comment by momipsl** [comment]
From an admin point of view it is better to upload smaller file collections by splitting them into separate directories and uploading each directory in turn.

However at the same time the formatter can also be updated so as to format one file at a time.  Therefore I will make the required code changes so that the files are processed one at a time rather than all at once.  Also I will update the formatted to output only blocks instead of blocks and lines as the latter are not being used at present.

**Comment by momipsl** [comment]
Have committed an update to the formatter so as to process files one at a time thereby reducing memory footprint.

**Comment by SebastienDenvil** [comment]
@jservonnat : let me know when you run a large ingestion phase. I will have a look to the resource consumption at that time.

**Comment by jservonnat** [comment]
ok!

**Comment by SebastienDenvil** [comment]
@jservonnat don't forget to give me a heads up before you perform ingestion (preferably a large one)

**Comment by jservonnat** [comment]
We should have a huge one for tomorrow ;).
