### ISSUE TITLE
Client library installation on CICLAD

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#31]
We need to be able to perform a light installation of Simulation-Metrics-CLI on ciclad. We are not root on this machine and thus we need a lightweight approach (ie not installing the full stack when we only need CLIs)
https://github.com/Prodiguer/prodiguer-docs/wiki/Simulation-Metrics-CLI

**Comment by momipsl** [comment]
There are two ways to do this.  Either create a new repo (e.g. prodiguer-metrics-cli) and then copy across the existing bash and python scripts from the prodiguer-shell.  Or upgrade the prodiguer-shell installer so that it takes a profile parameter (i.e. dev | web | mq | db | metrics-cli ..etc.) and then only downloads the assets that the profile requires.  The first option is easier the second option smarter.

If we go with the first option then 2 python dependencies will need to be available - tornado and requests.

**Comment by SebastienDenvil** [comment]
What about the "easy_install prodiguer-metrics-cli" approach?

**Comment by momipsl** [comment]
This will only install the python package and not the aliased shells scripts.  The shell scripts streamline the experience so that the user simply execute shell commands passing in the relevant parameters - i..e they do not need to know anything about the pythonic internals.

However if we now make the user responsible for setting up their own python venv and tell them that they should exclusively use python to invoke prodiguer-client commands / jobs then the "pip install prodiguer-metrics-cli" approach works,

Actually with regards to the idea of creating a separate client for the metrics, i.e. prodiguer-metrics-cli, we may as well simply create a prodiguer-client that includes the metrics commands.

**Comment by SebastienDenvil** [comment]
We don't want Simulation Metrics CLI users to write their own python to fetch a group of metrics or to add metrics in the database. Is that what you meant?

The package will provide access to functions and to metrics command (python script). Metrics command will of course provide the following capabilities. https://github.com/Prodiguer/prodiguer-docs/wiki/Simulation-Metrics-CLI We don't want users to write those python scripts. They will be in the python package.

**Comment by momipsl** [comment]
The code snippet above is clear on this point.  prodiguer-client will expose high level functions, the user simply invokes those functions passing required parameters.

Internally prodiguer-client will do things such as prepare a web-service request, call the web-service, decode the web-service response, return a result (e.g. a set of metrics).  Essentially prodiguer-client will be brain dead simple to use.

**Comment by SebastienDenvil** [comment]
Let's see the implication of this during your next stay. I think we can't avoid high level command lines doing what we have now with prodiguer-add-batch ... We don't really want to force user to write those python scripts (even if it is simple ...).

**Comment by SebastienDenvil** [comment]
I have seen Philippe today. He told arrow has been installed on ciclad

**Comment by ncaripsl** [comment]
[ncarenton@ciclad-ng ~]$ prodiguer-client-metrics-fetch-list

 /opt/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
2015-06-02T08:58:45 :: IPSL PRODIGUER-CLIENT INFO METRICS > list :: lmdz_jetlat
2015-06-02T08:58:45 :: IPSL PRODIGUER-CLIENT INFO METRICS > list :: nemo_latbandsandregions
2015-06-02T08:58:45 :: IPSL PRODIGUER-CLIENT INFO METRICS > list :: lmdz_pcmdi
2015-06-02T08:58:45 :: IPSL PRODIGUER-CLIENT INFO METRICS > list :: ipsl-extended-test-01-blocks
2015-06-02T08:58:45 :: IPSL PRODIGUER-CLIENT INFO METRICS > list :: nemo_pcmdi
2015-06-02T08:58:45 :: IPSL PRODIGUER-CLIENT INFO METRICS > list :: ipsl-extended-test-01-lines
-------------------------------------------------------------------------------

**Comment by momipsl** [comment]
The InsecureRequestWarning is not a blocker but is somewhat annoying.  We will need to bundle client side certificates and then specify these when invoking the remote API.

**Comment by SebastienDenvil** [comment]
Done
