### ISSUE TITLE
Not using CV aliases when deriving urls

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#37]
in this simulation
https://prodiguer-test-web.ipsl.fr/static/simulation.html?uid=26bd9c6e-b2b9-4806-9cc2-e3683b71bac8

experiment has been defined as AMIP so the working monitoring is:
https://esgf.extra.cea.fr/thredds/fileServer/work/mellull/LMDZOR/PROD/AMIP/AMIPCM5Bs05/MONITORING/index.html

You use an alias for the UI but you should not apply to derive the monitoring endpoints.
https://esgf.extra.cea.fr/thredds/fileServer/work/mellull/LMDZOR/PROD/amip/AMIPCM5Bs05/MONITORING/index.html

**Comment by momipsl** [comment]
This is actually problematic because when processing 0000 messages, the incoming controlled vocabulary related fields are parsed and their values substituted for the value specified in the relevant CV.  In this example the incoming experiment name AMIP was substituted by amip *as this is the CV value* - see [here](https://github.com/Prodiguer/prodiguer-cv/blob/master/data/experiment/amip.json).  

The solution to this problem is to store either both the raw and parsed field values or alternatively just the raw value.  Either way we would be able to write a quality control script to do the following:  "notify users who have defined incorrect CV values."

**Comment by SebastienDenvil** [comment]
Either way seems fine to me. We will enforce the CV for very specific cases like CMIP6 simulations.

**Comment by momipsl** [comment]
I prefer the 2 field strategy, i..e experiment and experiment_raw.  I will also do this for the following fields: activity, centre, machine, model, space.

**Comment by SebastienDenvil** [comment]
Done. Will be tested when ESGF is back online
