### ISSUE TITLE
For post processing jobs replace the Acc.Project column by a 

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#43]
Identifier is built this way:
postProcessingName.postProcessingName.postProcessingDate.postProcessingDimn.postProcessingComp.postProcessingFile

Don't use one of those custom fields if his value is null.

rebuild_fromWorkdir.19801231
creates_ts.19801231.Chunck3D.ATM.Post_1M_histmth

see
https://github.com/Prodiguer/prodiguer-docs/wiki/Monitoring-Message-Dictionary#2000

**Comment by SebastienDenvil** [comment]
It works but as initially specified:

Don't use one of those custom fields if his value is null.

rebuild_fromWorkdir.19801231
creates_ts.19801231.Chunck3D.ATM.Post_1M_histmth

**Comment by momipsl** [comment]
Now that I have some real data to test with I can see that the issue here is that you are encoding the post-processing fields in the message content with the string literal "null" rather than the JSON literal null.    I.E.  postProcessingComp: "null"  rather than postProcessingComp: null.  

The javascript null test reports true for the string literal "null" and hence they are appearing in the UI.

I have updated the message consumer to strip out fields marked with the string literal "null" and also the UI to do likewise.

**Comment by SebastienDenvil** [comment]
It seems that those are not properly displayed:
 creates_ts.19801231.Chunck3D.ATM.Post_1M_histmth
Should be : postProcessingName.postProcessingName.postProcessingDate.postProcessingDimn.postProcessingComp.postProcessingFile

example here. We cant distinguish between those identical create_ts.1850-01-01
https://prodiguer-test-web.ipsl.fr/static/simulation.detail.html?hashid=302080e3620c79597f49f626339e6796&tryID=1&uid=1ff82a28-d21d-4325-ad5c-bfb03a7505cb

**Comment by SebastienDenvil** [comment]
My bad. It comes from libIGCM
