### ISSUE TITLE
The previous tries button is confusing and might be removed

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#44]
When you select a try you don't have access to the future one and the count start from an empty string. https://prodiguer-test-web.ipsl.fr/static/simulation.monitoring.one.html?hashid=fb753c7f3b10dfec8c5307d147b52982&tryID=9&uid=6e1c7b3e-e12c-4c83-a757-257f0effb6f5

Thinking about it it is only needed to consider the latest try. Also it could enhance performance to only consider the last one.

**Comment by momipsl** [comment]
From the monitoring page the link is always to the latest try.  The links to previous tries from the detail page are there simply to aid debugging.  This has zero impact on performance.  

The empty value is simply there as a constraint of displaying the navigation link in a dropdown selector - I can replace this with text links instead.

However the real issue here is when someone has opened the detail page on try 3 (for example) and then X minutes later try 3 fails and try 4 is started, the detail page does not automatically refresh the data because it is only pointing at a specific try and thus does not receive a web-socket notification of the new try.  I can add this feature if requested but this will take a day or so (incl. testing).

**Comment by SebastienDenvil** [comment]
There is no need to develop the web socket you mentioned.

Also I think there is an obvious impact on performance because AFAIK you have to load every tries client side. If you load only the latest you have less to load and it is faster. The same apply server side, before sending to the client.

We really dont need the tries history whatsoever.

**Comment by momipsl** [comment]
Your assumptions about loading each try on the client side are wrong (read the code).  Only the current try being viewed is loaded.

Tries history may be irrelevant for user re-running TEST/DEVT simulations.  But I believe it is useful for debugging and when running PROD simulations.  Please confirm.

**Comment by SebastienDenvil** [comment]
Is that also true server side? only the current try being viewed has been loaded?

I confirm we dont have to expose this to users.

**Comment by momipsl** [comment]
https://github.com/Prodiguer/prodiguer-server/blob/master/prodiguer/web/endpoints/monitoring/fetch_one.py

Line 54 explicitly loads a single simulation try.

**Comment by momipsl** [comment]
For the monitoring front end we only load active simulations, i.e. the latest try.  See line 52 of the fetch-timeslice endpoint handler:

https://github.com/Prodiguer/prodiguer-server/blob/master/prodiguer/web/endpoints/monitoring/fetch_timeslice.py

**Comment by SebastienDenvil** [comment]
So it is true server side and client side. You can keep it for debugging if you need it.

But don't expose it to users.
