### ISSUE TITLE
Hermes cookies and cache

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#87]
each time we upgrade the front end we need to ask users to clear the cache and the cookies. This is painfull and not at all user friendly.

Could you imagine a scenario where the client check his version against the current one and clear cookies and cache if different? This check needs to be only the first time the page is loaded.

**Comment by asladeofgreen** [comment]
Solution to this is as follows:

1. HTML files are uncached ... this is done by modifying nginx.conf.

2. JS / CSS files are served from a version specific folder, e.t. 1.3.0.0, and hence are simply downloaded by the browser whenever the application is updated.  In nginx.conf I will add a cache expiration directive of 1 month so that old files are regularly deleted.

3. Cookies are refreshed between releases.

**Comment by asladeofgreen** [comment]
Steps 2. and 3. above are implemented.  Will update the nginx.conf files shortly.

**Comment by asladeofgreen** [comment]
Implemented - to be tested on next release.
